### PR TITLE
Modernize jellyfish

### PR DESCRIPTION
**Pull request by derrickburns**
Remove dead code, including hakken and code for GET /v1/device/data/{id} and GET /v1/synctasks/{id}. Remove storage module. Use flat env variables.

### CODE REVIEW

**Review by pazaan — DISMISSED** [review]
LGTM! 🚢

**Comment by derrickburns** [comment]
Address BACK-1724

**Comment by derrickburns** [comment]
@pazaan Deployed on Qa2

**Review by jamesraby — APPROVED** [review]
Reviewing from where Lenny left off - LGTM.  Good for you to get rid of dead code

**Comment by derrickburns** [comment]
@tjotala Testing in QA.

**Review by pazaan — APPROVED** [review]
LGTM! :shipit:

**Review by tjotala — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
