### PR TITLE
Request server-side encryption for data stored in S3 buckets

### PR DESCRIPTION
**Pull request by darinkrauss**
@jh-bate This is the single-line change to enable server-side encryption in S3 buckets.  The change to turn off the client-side encryption is a configuration-only change.

### CODE REVIEW

**Comment by jh-bate** [comment]
LGTM

**Comment by darinkrauss** [comment]
@jh-bate Updated to use server-side encryption with our key (rather than an AWS key). Let me know what you think.

**Comment by jh-bate** [comment]
LGTM as discussed feels like a more 'complete' solution

**Comment by darinkrauss** [comment]
@jhbate Can you check out the last commit?  Just updated the key/path to the data to use the user id rather than the metadata id to be less complicated.

**Pull request closed without merging**
