### PR TITLE
add 'bootstrap' to the hash data to ensure different IDs

### PR DESCRIPTION
**Pull request by jebeck**
@jh-bate or @darinkrauss I thought I'd put this up for review quick first to make sure I did it right before I update the tests since *all* the IDs in the API ingestion tests have to be updated because of it... (or at least I hope *all* of them have to be updated - that's the point!)

The point of this is to ensure we don't drop data on the floor that's been uploaded before after we deploy BtUTC. We need post-BtUTC to be different from pre-BtUTC IDs for all IDs. This solution is pretty much as arbitrary as any other...

### CODE REVIEW

**Comment by jebeck** [comment]
OK, preliminary results from testing locally:

Upload my OmniPod with pre-bootstrap uploader, pre-bootstrap jellyfish, database state:
screenshot 2015-08-04 15 19 02

Upload my OmniPod with BtUTC uploader, this branch of jellyfish (+ restart *everything* with runservers and having added a `export SCHEMA_VERSION=1`):
screenshot 2015-08-04 15 19 14

The difference in counts between version 0 and version 1 (1397 vs. 1348) must be due to differences in OmniPod data processing between pre-bootstrap and BtUTC uploader. I find it a little disturbing - I can't think off the top of my head what exactly would cause it, especially in my data, which has no time changes in it (so there was no overlap that's being corrected now or anything). So I'm investigating that now, although it may not relate directly to this PR unless it really is an ID clash problem.

**Comment by jebeck** [comment]
OK, with further investigation it seems there's a problem in the BtUTC version of the Insulet driver (what I was testing locally with before). My local testing of this change in the ID hash generation with the Dexcom went swimmingly, so I think it is ready for review now.

**Comment by jebeck** [comment]
I updated this to add `value` to the idFields for SMBGs as discussed after @gniezen's revelation that many BGMs only store readings at the resolution of one minute on the timestamps (for which the appropriate emoji is D:).

Still would like a review from @jh-bate or @darinkrauss before updating the tests. Meant to ask before, is there some particular reason for updating with an underscore too after each update - `hasher.update('_');`?? I followed that a little blindly from what was there already.

**Comment by darinkrauss** [comment]
@jebeck I think adding the bootstrap is fine, but if I understand correctly it shouldn't be necessary if we are doing the correct _schemaVersion checks when looking for duplicates (anything outside of the min and max shouldn't be considered for anything at all; effectively invisible).  This _schemaVersion check should be for any and all db queries for data.

I'm not positive, but I suspect the '_' is there to prevent a scenario like the following (if '_' wasn't there):

fields = ['a','bc']           # yields hash 'abc'
fields = ['ab', 'c']          # yields hash 'abc' (same -> bad!)

but with the added '_':

fields = ['a','bc']           # yields hash 'a_bc'
fields = ['ab', 'c']          # yields hash 'ab_c' (different -> good!)

**Comment by jebeck** [comment]
So our conversation about doing checks for min and max _schemaVersion happened after I'd already opened this pull request, I believe. But also I'm still not certain that's the correct approach, at least in terms of the uses we had planned for the `_schemaVersion` field. It seems like the division between `_schemaVersion` 0 and 1 (pre- and post-bootstrap) will eternally be the important line in the sand (in which case just adding a little salt to the hash is just as arbitrary and an easier change to make). Since the plan was to use _schemaVersion to version the models for *individual* types of data (basal vs. bolus, etc.), I can't see how specifying a min or max *across the board* (agnostic to data type) is ever going to be helpful. For example, say we come up with an entirely new basal data model and decide to bump to version 2 for that schema. We're living in hypothetical magical la-la land, so we successfully migrate old basal data from schema 1 to schema 2, and then when we're uploading new data, we only want to check for duplicates against the current schema - version 2. But for all other data we're still on version 1, so now we have to add new logic anyway, because the logic we added when doing the BtUTC deploy only accounted for checking for duplicates against a specific schema version for all data types...

Don't get me wrong, I definitely find adding 'bootstrap' to the hashes a decidedly inelegant solution, and it rankles. But I'm not terribly convinced (yet!) that it's uglier than other (more complex) solutions.

Thanks for explaining about the `_` - makes perfect sense!

**Comment by darinkrauss** [comment]
@jebeck Okay, that works. We can always update the hash later and regenerate as appropriate if we ever want to change/delete the extra salt.

**Comment by jebeck** [comment]
OK, I fixed the tests. Now going to add one more ingestion test to prove to ourselves that the change in 1a3e979e2039851fa455fc8f25edc171005a1519 does what we want - generates different IDs for two SMBGs with different values but same (within minute resolution) device time.

**Pull request merged**
